# Generated by Django 4.1.3 on 2022-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_customercontact_delete_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontact',
            old_name='adsress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
