# Generated by Django 4.1.3 on 2022-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_adsress_customercontact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet')], max_length=50, null=True)),
            ],
        ),
    ]
