# Generated by Django 4.0.7 on 2022-11-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_manufacturingplan_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
