# Generated by Django 4.0.7 on 2022-11-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_manufacturingplan_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingplan',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
