# Generated by Django 4.0.7 on 2022-11-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_manufacturingplan_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingplan',
            name='is_open',
        ),
        migrations.AddField(
            model_name='manufacturingplan',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=50, null=True),
        ),
    ]
