# Generated by Django 4.0.7 on 2022-11-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_inventory_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
