# Generated by Django 4.0.7 on 2022-11-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
