# Generated by Django 4.0.7 on 2022-11-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_task_quantity_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, choices=[('Khách hàng', 'Khách hàng'), ('Khách hàng tiềm năng', 'Khách hàng tiềm năng'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact', to='core.customer'),
        ),
    ]
