# Generated by Django 4.0.7 on 2022-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_customer_type_alter_customercontact_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('cp1', 'cp1'), ('cp2', 'cp2')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(to='core.component', verbose_name='xxx'),
        ),
    ]
