# Generated by Django 4.0.7 on 2022-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_component_product_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(blank=True, null=True, to='core.component', verbose_name='xxx'),
        ),
    ]
