# Generated by Django 4.0.7 on 2022-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_supplier_alter_product_component_component_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_end',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_start',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
