# Generated by Django 4.0.7 on 2022-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
