# Generated by Django 4.0.7 on 2022-11-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_manufacturingplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='invnetory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
    ]
