# Generated by Django 4.0.7 on 2022-11-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_task_invnetory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='invnetory',
        ),
        migrations.AddField(
            model_name='task',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse'),
        ),
    ]
