# Generated by Django 4.0.7 on 2022-11-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_inventory_warehouse_team_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse'),
        ),
    ]
