# Generated by Django 4.0.7 on 2022-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_orderline_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='component',
        ),
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_camera', to='core.component'),
        ),
        migrations.AddField(
            model_name='product',
            name='chip',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_chip', to='core.component'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_screen', to='core.component'),
        ),
    ]
