# Generated by Django 4.0.7 on 2022-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_product_component_product_camera_product_chip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(blank=True, choices=[('chip', 'chip'), ('camera', 'camera')], max_length=50, null=True),
        ),
    ]
