# Generated by Django 4.1.3 on 2022-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_customer_size_customer_status_customer_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
