# Generated by Django 4.1.3 on 2022-11-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
