# Generated by Django 4.1.3 on 2022-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_customer_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='company_logo/'),
        ),
    ]
